# Используем Node.js для сборки Angular приложения
FROM node:16 AS build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем остальной код и билдим проект
COPY . .
RUN npm run build --prod

# Сервируем билд через Nginx
FROM nginx:alpine
COPY --from=build /app/dist/your-angular-project /usr/share/nginx/html

# Открываем порт 80
EXPOSE 80

# Nginx будет запущен автоматически
